apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
spec:
  minReadySeconds: 30
  selector:
    matchLabels:
      app: tomcat
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat:9.0

--- 

apiVersion: v1
kind: Service
metadata:
  name: tomcat-service

spec:
  selector: 
    app: tomcat
  
  ports:
    - name: http
      port: 80
      nodePort: 30082 # only for NotPort > 30,000
    
  type: NodePort #ClusterIP inside cluster

---

apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: tomcat-ingress
spec:
  defaultBackend:
    service:
      name: tomcat-service
      port:
        number: 80
  rules:
  - host: kubernetes.docker.internal
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  tomcat-service
            port: 
              number: 80
    