apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service

spec:
  selector: 
    app: mongodb
  
  ports:
    - name: http
      port: 27017
      nodePort: 30081 # only for NotPort > 30,000
    
  type: NodePort #ClusterIP inside cluster

---

apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: mongodb-ingress
spec:
  defaultBackend:
    service:
      name: mongodb-service
      port:
        number: 27017
  rules:
  - host: kubernetes.docker.internal
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name:  mongodb-service
            port: 
              number: 27017
